### ISSUE TITLE
Is react-mocks (plural) a better name for this project?

### ISSUE THREAD

**Issue by skidding** [skidding/react-mock#13]
Which is better, react-mock or react-mocks?

I like the former because it's more brief, but I'm suspecting the latter sounds more natural. After all, the project is a collection of mocks.

It's a good time to make this decision as the project is brand new.

**Comment by alp82** [comment]
I vote for `react-mock`. Plural forms are unusual, even if collections are addressed. E.g. database table/collection names are mostly singular, but they contain multiple entries.

**Comment by skidding** [comment]
`react-mock` it is!
